import { getProject } from '@theatre/core';
import {
  LYRICS, buildTimeline, TOTAL_DURATION, GAP_ASSETS, COLLAGE_ASSETS,
  HERO_WINDOWS, assetPath, moodAt,
} from './lyrics-data.mjs';
import { initScene, IS_MOBILE } from './scene/scene3d.js';
import './style.css';

const audio = document.getElementById('track');
const stack = document.getElementById('stack');
const stageEl = document.getElementById('stage');
const progressFill = document.getElementById('progress-fill');
const playBtn = document.getElementById('play-btn');
const finaleEl = document.getElementById('finale');
const finaleFlourish = document.getElementById('finale-flourish');
const introVinyl = document.getElementById('intro-vinyl');
const sceneCanvas = document.getElementById('scene-canvas');
const root = document.documentElement;

introVinyl.innerHTML = '<div class="vinyl-disc"></div>';

// Finale flourish — the handful of illustrations that don't belong to any
// specific lyric get their one moment here, scattered loosely around the
// closing message instead of sitting unused.
[
  { asset:'two-hearts.png', top:'12%', left:'8%' },
  { asset:'ribbon.png', top:'18%', left:'auto', right:'10%' },
  { asset:'sparkles.png', top:'70%', left:'12%' },
  { asset:'love-letter.png', top:'68%', left:'auto', right:'9%' },
].forEach(cue => {
  const wrap = document.createElement('div');
  wrap.className = 'asset-wrap';
  wrap.style.top = cue.top;
  wrap.style.left = cue.left ?? 'auto';
  if (cue.right) wrap.style.right = cue.right;
  wrap.innerHTML = `<img src="${assetPath(cue.asset)}" alt="" loading="lazy">`;
  finaleFlourish.appendChild(wrap);
});

const TIMELINE = buildTimeline(LYRICS, TOTAL_DURATION);
const scene = initScene(sceneCanvas);

/**
 * Line slots are centered (left:50%) so they need translate(-50%,-50%) to
 * stay anchored; asset/collage wraps live directly under #stage and are
 * already edge-anchored horizontally (left/right clamp), so only their
 * vertical centering should come from the transform, or Theatre's own x/y
 * would double-offset them.
 */
function applyTransform(el, v, { centerX = true } = {}){
  if (!v) return;
  const x = v.x || 0, y = v.y || 0, scale = v.scale ?? 1, rotate = v.rotate || 0;
  const tx = centerX ? `calc(-50% + ${x}px)` : `${x}px`;
  el.style.transform = `translate(${tx}, calc(-50% + ${y}px)) scale(${scale}) rotate(${rotate}deg)`;
  el.style.opacity = v.opacity ?? 1;
  if (v.blur !== undefined) el.style.filter = v.blur > 0.05 ? `blur(${v.blur}px)` : 'none';
  if (v.weight !== undefined) el.style.fontVariationSettings = `'opsz' ${IS_MOBILE ? 38 : 90}, 'wght' ${Math.round(v.weight)}`;
}

function buildAssetWrap(cue, { topPercent, tier = 'accent' }){
  const wrap = document.createElement('div');
  wrap.className = `asset-wrap side-${cue.side}${tier === 'ambient' ? ' tier-ambient' : ''}`;
  wrap.style.top = topPercent + '%';
  wrap.innerHTML = `<img src="${assetPath(cue.asset)}" alt="" loading="lazy">`;
  stageEl.appendChild(wrap);
  return wrap;
}

function buildCollageWrap(cue, topPercent){
  const wrap = document.createElement('div');
  wrap.className = `collage-wrap side-${cue.side}`;
  wrap.style.top = topPercent + '%';
  wrap.style.left = cue.side === 'left' ? '-2%' : 'auto';
  wrap.style.right = cue.side === 'right' ? '-2%' : 'auto';
  wrap.innerHTML = `<img src="${assetPath(cue.asset)}" alt="" loading="lazy">`;
  stageEl.appendChild(wrap);
  return wrap;
}

/**
 * Real timing data (word-level, transcription-grounded — see ATTRIBUTION.md)
 * from lyrics-data.mjs. Real choreography (position/opacity/scale/rotate/
 * blur/weight for every line, curated accent, camera, mood and the three
 * Three.js hero objects) from a genuine Theatre.js sequence in
 * assets/theatre-state.json (generated by tools/build-theatre-state.mjs —
 * see that file for why it's generated rather than hand-authored in
 * Theatre.js Studio's visual editor). Rendering here is just: scrub
 * `sheet.sequence.position` to audio.currentTime every frame, and apply
 * whatever values each object's onValuesChange hands back. No custom
 * per-frame motion math lives in this file — word-level kinetic entrance
 * and the sung/unsung sweep are the one deliberate exception, staying
 * outside Theatre.js since they're discrete per-timestamp state, not a
 * continuously tweened value (same reasoning the previous build used for
 * the sung-highlight).
 */
async function main(){
  const state = await (await fetch('/assets/theatre-state.json')).json();
  const project = getProject('My Sweetheart', { state });
  const sheet = project.sheet('Lyrics');
  await project.ready;

  const introObj = sheet.object('intro-vinyl', { opacity:0, scale:1 });
  introObj.onValuesChange(v => applyTransform(introVinyl, v));

  const introNotesWrap = buildAssetWrap({ asset:'musical-notes.png', side:'right' }, { topPercent: 24, tier:'ambient' });
  const introNotesObj = sheet.object('intro-notes', { opacity:0, scale:1, rotate:0 });
  introNotesObj.onValuesChange(v => applyTransform(introNotesWrap, v, { centerX:false }));

  const moodObj = sheet.object('mood', { hue:280, warmth:0.15 });
  moodObj.onValuesChange(v => {
    root.style.setProperty('--mood-hue', v.hue.toFixed(1));
    root.style.setProperty('--mood-warmth', v.warmth.toFixed(2));
    scene.setParticleHue(v.hue);
  });

  const cameraObj = sheet.object('camera', { z:8, fov:45, yaw:0 });
  cameraObj.onValuesChange(v => {
    scene.camera.position.z = v.z;
    scene.camera.position.x = Math.sin(v.yaw) * 1.6;
    scene.camera.fov = v.fov;
    scene.camera.lookAt(0, 0, 0);
    scene.camera.updateProjectionMatrix();
  });

  // Hero glass objects are scaled down further on small screens (the same
  // world-unit size reads much bigger against a narrow portrait frustum),
  // and their `x` track is a fraction of the camera's live visible
  // half-width rather than a fixed world offset — see the comment in
  // tools/build-theatre-state.mjs for why.
  const HERO_MOBILE_SCALE = IS_MOBILE ? 0.6 : 1;
  HERO_WINDOWS.forEach(w => {
    const obj = sheet.object(`hero-${w.type}`, { scale:0, x:0, y:0 });
    const mesh = scene.heroObjects[w.type];
    obj.onValuesChange(v => {
      mesh.visible = v.scale > 0.01;
      mesh.scale.setScalar(v.scale * HERO_MOBILE_SCALE);
      const distance = scene.camera.position.z;
      const vFov = scene.camera.fov * Math.PI / 180;
      const halfHeight = Math.tan(vFov / 2) * distance;
      const halfWidth = halfHeight * scene.camera.aspect;
      mesh.position.set(v.x * halfWidth, v.y, 0);
    });

    (COLLAGE_ASSETS[w.type] || []).forEach((cue, cIdx) => {
      const wrap = buildCollageWrap(cue, 22 + cIdx * 30);
      const cObj = sheet.object(`collage-${w.type}-${cIdx}`, { opacity:0, scale:1, rotate:0 });
      cObj.onValuesChange(v => applyTransform(wrap, v, { centerX:false }));
    });
  });

  let lineIndex = 0;
  const wordWatchers = [];

  // A randomized subset of emotionally-loaded words gets a pink highlight
  // instead of plain ink, re-rolled on every page load.
  const STOP_WORDS = new Set(['the','a','an','of','in','on','with','that','so','just','still','it','by','me','you','i','am','our']);
  const PRIORITY_WORDS = new Set(['sweetheart','love','true','dreaming','dreams','dream','moonlight','whisper','sweetheart?']);
  function randomizeAccents(wordEls){
    for (const wd of wordEls){
      const clean = wd.el.textContent.toLowerCase().replace(/[.,!?"']/g, '');
      if (STOP_WORDS.has(clean)) continue;
      const chance = PRIORITY_WORDS.has(clean) ? 0.8 : 0.28;
      wd.el.classList.toggle('word-special', Math.random() < chance);
    }
  }

  TIMELINE.forEach((entry) => {
    if (entry.type === 'gap'){
      const key = entry.start.toFixed(2);
      const cue = GAP_ASSETS[key];
      if (!cue) return;
      const wrap = buildAssetWrap(cue, { topPercent: 32 + (lineIndex % 3) * 14, tier:'ambient' });
      const obj = sheet.object(`gap-${key}`, { opacity:0, scale:1, rotate:0 });
      obj.onValuesChange(v => applyTransform(wrap, v, { centerX:false }));
      return;
    }

    const i = lineIndex++;
    const el = document.createElement('div');
    el.className = 'line-slot';

    if (entry.section){
      const tag = document.createElement('div');
      tag.className = 'section-tag';
      tag.textContent = entry.section;
      el.appendChild(tag);
    }

    const lineEl = document.createElement('div');
    lineEl.className = 'lyric-line' + (entry.type === 'spoken' ? ' spoken' : '');
    const wordEls = [];
    (entry.words || []).forEach((w, wi) => {
      const span = document.createElement('span');
      span.className = 'word';
      span.textContent = w.w;
      lineEl.appendChild(span);
      if (wi < entry.words.length - 1) lineEl.appendChild(document.createTextNode(' '));
      wordEls.push({ el: span, start: w.s, end: w.e });
    });
    el.appendChild(lineEl);
    stack.appendChild(el);

    const lineObj = sheet.object(`line-${i}`, { x:0, y:0, opacity:1, scale:1, rotate:0, blur:0, weight:600 });
    lineObj.onValuesChange(v => applyTransform(el, v));

    if (entry.asset){
      const wrap = buildAssetWrap({ asset: entry.asset, side: entry.side || 'left' }, { topPercent: 30 + (i % 4) * 12 });
      const assetObj = sheet.object(`asset-${i}`, { opacity:0, scale:1, rotate:0 });
      assetObj.onValuesChange(v => applyTransform(wrap, v, { centerX:false }));
    }

    randomizeAccents(wordEls);
    wordWatchers.push({ start: entry.start, end: entry.end, words: wordEls });
  });

  // ------------------------------------------------------------------
  // Word-by-word highlight + kinetic entrance — a discrete state per real
  // timestamp, not a tween, so it stays plain per-frame comparison rather
  // than a Theatre.js track (see main() doc comment above).
  // ------------------------------------------------------------------
  const WORD_LEAD = 0.55;
  function renderWords(t){
    for (const line of wordWatchers){
      if (t < line.start - 3 || t > line.end + 3) continue;
      for (const wd of line.words){
        const isNow = t >= wd.start && t < wd.end;
        const isSung = t >= wd.end;
        wd.el.classList.toggle('is-now', isNow);
        wd.el.classList.toggle('is-sung', isSung && !isNow);
        wd.el.classList.toggle('word-entered', t >= wd.start - WORD_LEAD);
      }
    }
  }

  let rafId = null;
  let lastT = performance.now();
  function frame(now){
    const dt = Math.min((now - lastT) / 1000, 0.1);
    lastT = now;
    const t = audio.currentTime;
    sheet.sequence.position = t;
    renderWords(t);
    progressFill.style.width = (t / TOTAL_DURATION * 100).toFixed(2) + '%';
    scene.render(dt);
    rafId = requestAnimationFrame(frame);
  }

  function togglePlay(){
    if (audio.paused){
      finaleEl.classList.remove('visible');
      stageEl.classList.remove('hidden');
      if (audio.ended || audio.currentTime >= TOTAL_DURATION - 0.05) audio.currentTime = 0;
      audio.play();
      playBtn.classList.add('is-playing');
      lastT = performance.now();
      if (!rafId) rafId = requestAnimationFrame(frame);
    } else {
      audio.pause();
      playBtn.classList.remove('is-playing');
    }
  }
  playBtn.addEventListener('click', togglePlay);

  audio.addEventListener('ended', () => {
    playBtn.classList.remove('is-playing');
    stageEl.classList.add('hidden');
    finaleEl.classList.add('visible');
    if (rafId){ cancelAnimationFrame(rafId); rafId = null; }
  });

  // Render the very first frame (t=0) immediately so the page isn't blank
  // before the visitor presses play.
  sheet.sequence.position = 0;
  renderWords(0);
  const initialMood = moodAt(0);
  root.style.setProperty('--mood-hue', initialMood.hue);
  root.style.setProperty('--mood-warmth', initialMood.warmth);
  scene.setParticleHue(initialMood.hue);
  scene.render(0);
}

main().catch(err => console.error('Theatre.js/Three.js init failed:', err));
